---
- name: starting stuff
  hosts: rhel9
  gather_facts: no
  tasks:
    - name: getting fw info
      ansible.posix.firewalld_info:
        active_zones: true
      #  zones:
      register: fw_info

    - name: open some ports
      ansible.posix.firewalld:
        permanent: true
        zone: public
        port: "{{ item }}"
        immediate: true 
        state: enabled
      loop:
        - 80/tcp
        - 53/udp
        - 443/tcp
        - 68/udp 
    
    - name: show stuff
      debug:
       # var: fw.firewalld_info.default_zone
        var: fw_info
